apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: controller
  name: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - image: rodneybarreto/livraria-controller
        imagePullPolicy: "Always"
        name: controller
        ports:
        - containerPort: 3000
        env:
        - name: INVENTORY_HOST
          value: http://inventory.produtos.net:3002
        - name: SHIPPING_HOST
          value: http://shipping:3001
